"""
Report File Writer Tool — Student D
====================================
Generates professional Markdown interview preparation reports and saves them
to the local filesystem. Supports individual candidate reports and
multi-candidate comparison tables.

This tool is the system's final output stage — it produces polished,
print-ready documents for the hiring manager.

Features:
    - Professional Markdown with YAML front matter
    - Timestamped filenames for traceability
    - Candidate snapshot tables
    - Comparison report generation
    - Audit footer with generation metadata
"""

import os
from datetime import datetime
from typing import Optional

from langchain_core.tools import tool
from pydantic import BaseModel, Field


class ReportGenerationResult(BaseModel):
    """Result of generating an interview preparation report.

    Attributes:
        success: Whether the report was successfully generated.
        file_path: Absolute path to the generated report file.
        file_size_kb: Size of the generated file in KB.
        candidate_name: Name of the candidate in the report.
        job_title: Job title the candidate applied for.
        report_type: Type of report (INDIVIDUAL or COMPARISON).
        timestamp: ISO timestamp when the report was generated.
        error_message: Error message if report generation failed.
    """

    success: bool = Field(description="Whether the report was successfully generated")
    file_path: str = Field(description="Absolute path to the generated report file")
    file_size_kb: float = Field(default=0.0, description="Size of the generated file in KB")
    candidate_name: str = Field(default="", description="Name of the candidate")
    job_title: str = Field(default="", description="Job title applied for")
    report_type: str = Field(default="INDIVIDUAL", description="INDIVIDUAL or COMPARISON")
    timestamp: str = Field(default="", description="ISO timestamp of generation")
    error_message: Optional[str] = Field(default=None, description="Error message if failed")


@tool
def report_file_writer(
    output_dir: str,
    report_type: str,
    candidate_name: str = "",
    job_title: str = "",
    report_content: str = "",
    match_score: int = 0,
    assessment_score: float = 0.0,
    assessment_pass_status: str = "",
    recommendation: str = "",
    comparison_data: Optional[str] = None,
) -> dict:
    """Generate a professional Markdown interview report and save it locally.

    Supports two report types:
    - 'individual': Interview preparation guide for a single candidate.
    - 'comparison': Side-by-side comparison of multiple candidates for a vacancy.

    Args:
        output_dir: Directory where the report should be saved. Created if needed.
        report_type: Type of report — 'individual' or 'comparison'.
        candidate_name: Full name of the candidate (for individual reports).
        job_title: Title of the job the candidate is being evaluated for.
        report_content: Main Markdown content generated by the Interview Strategist agent.
        match_score: Overall match score (0-100) from the Job Matcher agent.
        assessment_score: Assessment score percentage from the Assessment Coordinator.
        assessment_pass_status: Assessment pass status (PASS/BORDERLINE/FAIL).
        recommendation: Final recommendation (PROCEED/PROCEED_WITH_CAUTION/DO_NOT_PROCEED).
        comparison_data: JSON string of multiple candidate data (for comparison reports).

    Returns:
        dict: Report generation result with file path and metadata.
    """
    if report_type == "individual":
        result: ReportGenerationResult = _generate_individual_report(
            output_dir=output_dir,
            candidate_name=candidate_name,
            job_title=job_title,
            report_content=report_content,
            match_score=match_score,
            assessment_score=assessment_score,
            assessment_pass_status=assessment_pass_status,
            recommendation=recommendation,
        )
    elif report_type == "comparison":
        result = _generate_comparison_report(
            output_dir=output_dir,
            job_title=job_title,
            comparison_data=comparison_data or "[]",
        )
    else:
        result = ReportGenerationResult(
            success=False,
            file_path="",
            error_message=f"Unknown report_type: {report_type}. Use 'individual' or 'comparison'.",
        )

    return result.model_dump()


def _generate_individual_report(
    output_dir: str,
    candidate_name: str,
    job_title: str,
    report_content: str,
    match_score: int,
    assessment_score: float,
    assessment_pass_status: str,
    recommendation: str,
) -> ReportGenerationResult:
    """Generate an individual candidate interview preparation report.

    Args:
        output_dir: Directory to save the report.
        candidate_name: Candidate's full name.
        job_title: Job title.
        report_content: Main content from the Interview Strategist.
        match_score: Match score from Agent 2.
        assessment_score: Assessment percentage from Agent 3.
        assessment_pass_status: PASS/BORDERLINE/FAIL from Agent 3.
        recommendation: Final recommendation from Agent 4.

    Returns:
        ReportGenerationResult: Generation result.
    """
    try:
        os.makedirs(output_dir, exist_ok=True)

        timestamp: str = datetime.now().isoformat()
        safe_name: str = candidate_name.lower().replace(" ", "_")
        safe_name = "".join(c for c in safe_name if c.isalnum() or c == "_")
        date_str: str = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename: str = f"interview_guide_{safe_name}_{date_str}.md"
        file_path: str = os.path.join(output_dir, filename)

        # Recommendation emoji mapping
        recommendation_emoji: dict[str, str] = {
            "PROCEED": "✅",
            "PROCEED_WITH_CAUTION": "⚠️",
            "DO_NOT_PROCEED": "❌",
        }
        emoji: str = recommendation_emoji.get(recommendation, "❓")

        # Assessment status emoji
        assessment_emoji: dict[str, str] = {
            "PASS": "✅",
            "BORDERLINE": "⚠️",
            "FAIL": "❌",
        }
        assess_emoji: str = assessment_emoji.get(assessment_pass_status, "❓")

        # Build the full report
        full_report: str = f"""---
title: Interview Preparation Guide
candidate: {candidate_name}
position: {job_title}
match_score: {match_score}/100
assessment_score: {assessment_score:.1f}%
assessment_status: {assessment_pass_status}
recommendation: {recommendation}
generated_at: {timestamp}
generated_by: HR Recruitment Pipeline MAS
---

# {emoji} Interview Preparation Guide

## Candidate Snapshot

| Field | Details |
|-------|---------|
| **Candidate** | {candidate_name} |
| **Position** | {job_title} |
| **Match Score** | {match_score}/100 |
| **Assessment Score** | {assessment_score:.1f}% {assess_emoji} |
| **Assessment Status** | {assessment_pass_status} |
| **Recommendation** | {recommendation} {emoji} |
| **Generated** | {timestamp} |

---

{report_content}

---

## Audit Information

> **Note:** This report was automatically generated by the HR Recruitment Pipeline
> Multi-Agent System. All data is sourced from the candidate's resume, the internal
> job database, and the auto-generated assessment results. **No data was sent to
> any external cloud service.**

| Audit Field | Value |
|-------------|-------|
| Report ID | `{safe_name}_{date_str}` |
| Pipeline Version | 1.0.0 |
| LLM Engine | Ollama (Local) |
| Generated At | {timestamp} |
"""

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(full_report)

        file_size_kb: float = round(os.path.getsize(file_path) / 1024, 2)

        return ReportGenerationResult(
            success=True,
            file_path=file_path,
            file_size_kb=file_size_kb,
            candidate_name=candidate_name,
            job_title=job_title,
            report_type="INDIVIDUAL",
            timestamp=timestamp,
        )

    except PermissionError:
        return ReportGenerationResult(
            success=False,
            file_path="",
            candidate_name=candidate_name,
            job_title=job_title,
            error_message=f"Permission denied: Cannot write to {output_dir}",
        )
    except Exception as e:
        return ReportGenerationResult(
            success=False,
            file_path="",
            candidate_name=candidate_name,
            job_title=job_title,
            error_message=f"Report generation failed: {type(e).__name__}: {str(e)}",
        )


def _generate_comparison_report(
    output_dir: str,
    job_title: str,
    comparison_data: str,
) -> ReportGenerationResult:
    """Generate a multi-candidate comparison report for a vacancy.

    Args:
        output_dir: Directory to save the report.
        job_title: Job title for the vacancy.
        comparison_data: JSON string with list of candidate comparison dicts.

    Returns:
        ReportGenerationResult: Generation result.
    """
    import json

    try:
        os.makedirs(output_dir, exist_ok=True)

        candidates: list[dict] = json.loads(comparison_data)
        timestamp: str = datetime.now().isoformat()
        date_str: str = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_title: str = job_title.lower().replace(" ", "_")
        safe_title = "".join(c for c in safe_title if c.isalnum() or c == "_")
        filename: str = f"comparison_{safe_title}_{date_str}.md"
        file_path: str = os.path.join(output_dir, filename)

        # Build comparison table
        table_header: str = "| # | Candidate | Match Score | Assessment Score | Assessment Status | Recommendation |\n"
        table_sep: str = "|---|-----------|-------------|-----------------|-------------------|----------------|\n"
        table_rows: str = ""

        for i, cand in enumerate(candidates, 1):
            table_rows += (
                f"| {i} | {cand.get('candidate_name', 'N/A')} | "
                f"{cand.get('match_score', 'N/A')}/100 | "
                f"{cand.get('assessment_score', 'N/A')}% | "
                f"{cand.get('assessment_pass_status', 'N/A')} | "
                f"{cand.get('recommendation', 'N/A')} |\n"
            )

        report: str = f"""---
title: Candidate Comparison Report
position: {job_title}
candidates_compared: {len(candidates)}
generated_at: {timestamp}
generated_by: HR Recruitment Pipeline MAS
---

# 📊 Candidate Comparison Report — {job_title}

**Date:** {timestamp}  
**Candidates Evaluated:** {len(candidates)}

## Ranking Summary

{table_header}{table_sep}{table_rows}

## Detailed Analysis

"""
        for i, cand in enumerate(candidates, 1):
            report += f"""### {i}. {cand.get('candidate_name', 'Unknown')}

- **Match Score:** {cand.get('match_score', 'N/A')}/100
- **Assessment Score:** {cand.get('assessment_score', 'N/A')}%
- **Strengths:** {cand.get('strengths', 'N/A')}
- **Concerns:** {cand.get('concerns', 'N/A')}
- **Recommendation:** {cand.get('recommendation', 'N/A')}

---

"""

        report += f"""
## Audit Information

> This comparison report was automatically generated by the HR Recruitment Pipeline MAS.
> No data was sent to any external cloud service.

*Report ID: comparison_{safe_title}_{date_str}*
"""

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(report)

        file_size_kb: float = round(os.path.getsize(file_path) / 1024, 2)

        return ReportGenerationResult(
            success=True,
            file_path=file_path,
            file_size_kb=file_size_kb,
            candidate_name=f"{len(candidates)} candidates",
            job_title=job_title,
            report_type="COMPARISON",
            timestamp=timestamp,
        )

    except json.JSONDecodeError as e:
        return ReportGenerationResult(
            success=False,
            file_path="",
            job_title=job_title,
            error_message=f"Invalid JSON in comparison_data: {str(e)}",
        )
    except Exception as e:
        return ReportGenerationResult(
            success=False,
            file_path="",
            job_title=job_title,
            error_message=f"Comparison report failed: {type(e).__name__}: {str(e)}",
        )
